stages:
  - Build
  - Publish

Build:
  stage: Build
  image:
    name: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - ./image.sh build

Push:
  secrets:
    DOCKER_CONFIG:
      vault: push/docker-config.json@containers.harderthanitneedstobe.com
  only:
    refs:
      - main
  stage: Publish
  image:
    name: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - ./image.sh push
