stages:
  - Build Containers

Build:
  stage: Build Containers
  image:
    name: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - ./build.sh build
