steps:
  - id: build-ubuntu
    waitFor: [ '-' ]
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/ubuntu:${_UBUNTU_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/ubuntu:$COMMIT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/ubuntu:${_UBUNTU_VERSION}-$COMMIT_SHA',
            '-f', 'images/ubuntu/${_UBUNTU_VERSION}/Dockerfile',
            'images/ubuntu/${_UBUNTU_VERSION}',
    ]
  - id: build-golang
    waitFor: [ '-' ]
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/golang:${_GOLANG_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/golang:$COMMIT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/golang:${_GOLANG_VERSION}-$COMMIT_SHA',
            '-f', 'images/golang/${_GOLANG_VERSION}/Dockerfile',
            'images/golang/${_GOLANG_VERSION}',
    ]
  - id: build-node
    waitFor: [ '-' ]
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/node:${_NODE_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/node:$COMMIT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/node:${_NODE_VERSION}-$COMMIT_SHA',
            '-f', 'images/node/${_NODE_VERSION}/Dockerfile',
            'images/node/${_NODE_VERSION}',
    ]
  ## Push ubuntu images.
  - id: 'push-ubuntu-1'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/ubuntu:${_UBUNTU_VERSION}' ]
    waitFor:
      - 'build-ubuntu'
  - id: 'push-ubuntu-2'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/ubuntu:$COMMIT_SHA' ]
    waitFor:
      - 'build-ubuntu'
  - id: 'push-ubuntu-3'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/ubuntu:${_UBUNTU_VERSION}-$COMMIT_SHA' ]
    waitFor:
      - 'build-ubuntu'
  ## Push golang images.
  - id: 'push-golang-1'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/golang:${_GOLANG_VERSION}' ]
    waitFor:
      - 'build-golang'
  - id: 'push-golang-2'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/golang:$COMMIT_SHA' ]
    waitFor:
      - 'build-golang'
  - id: 'push-golang-3'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/golang:${_GOLANG_VERSION}-$COMMIT_SHA' ]
    waitFor:
      - 'build-golang'
  ## Push node images.
  - id: 'push-node-1'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/node:${_NODE_VERSION}' ]
    waitFor:
      - 'build-node'
  - id: 'push-node-2'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/node:$COMMIT_SHA' ]
    waitFor:
      - 'build-node'
  - id: 'push-node-3'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/monetr/build-containers/node:${_NODE_VERSION}-$COMMIT_SHA' ]
    waitFor:
      - 'build-node'
substitutions:
  _UBUNTU_VERSION: '20.04'
  _GOLANG_VERSION: '1.17.0'
  _NODE_VERSION: '16.5.0-buster'

