name: Build

on:
  push: { }
  pull_request: { }


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mainTag: containers.monetr.dev/golang
            path: images/golang/
            version: 1.16.3
          - mainTag: containers.monetr.dev/ubuntu
            path: images/ubuntu/
            version: 20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ${{ matrix.path }}${{ matrix.version }}/Dockerfile
          context: ${{ matrix.path }}${{ matrix.version }}
          tags: ${{ matrix.maintTag }}:${{ matrix.version }}
