name: Build

on:
  push:
    branches:
      - main


jobs:
  docker:
    environment: containers.monetr.dev
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: postgres
            version: 13
          - path: golang
            version: 1.16.3
          - path: node
            version: 15.14.0-buster
          - path: ubuntu
            version: 20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate Tag
        id: tag
        run: |
          echo ::set-output name=POST_TAG::$(date +%Y.%m.%d)
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          registry: containers.monetr.dev
          username: ${{ secrets.containers_push_username }}
          password: ${{ secrets.containers_push_password }}
          dockerfile: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
          path: images/${{ matrix.path }}/${{ matrix.version }}
          tags: ${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
          repository: ${{ matrix.path }}

#      - name: Login to containers.monetr.dev
#        uses: docker/login-action@v1
#        with:
#          registry: containers.monetr.dev
#          username: ${{ secrets.containers_push_username }}
#          password: ${{ secrets.containers_push_password }}
#      #      - name: Login to ghcr.io
#      #        uses: docker/login-action@v1
#      #        with:
#      #          registry: ghcr.io
#      #          username: ${{ github.actor }}
#      #          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build Image
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          file: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
#          context: images/${{ matrix.path }}/${{ matrix.version }}
#          tags: containers.monetr.dev/${{ matrix.path }}:${{ matrix.version }}
##            ghcr.io/${{ github.repository_owner }}/build-containers/${{ matrix.path }}:${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
