name: Build

on:
  push:
    branches:
      - main

#          - path: golang
#          version: 1.16.3
#            - path: node
#              version: 15.14.0-buster
#        - path: ubuntu
#          version: 20.04

jobs:
  docker:
    environment: containers.monetr.dev
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: postgres
            version: 13
    steps:
      - uses: actions/checkout@v2
      - name: Generate Tag
        id: tag
        run: |
          echo ::set-output name=POST_TAG::$(date +%Y.%m.%d)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to containers.monetr.dev
        uses: docker/login-action@v1
        with:
          registry: containers.monetr.dev
          username: ${{ secrets.containers_push_username }}
          password: ${{ secrets.containers_push_password }}
      #      - name: Login to ghcr.io
      #        uses: docker/login-action@v1
      #        with:
      #          registry: ghcr.io
      #          username: ${{ github.actor }}
      #          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
          context: images/${{ matrix.path }}/${{ matrix.version }}
          tags: containers.monetr.dev/${{ matrix.path }}:${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
#            ghcr.io/${{ github.repository_owner }}/build-containers/${{ matrix.path }}:${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
