name: Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    environment: containers.monetr.dev
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: golang
            version: 1.17.0
          - path: node
            version: 16.5.0-buster
          - path: postgres
            version: 13
          - path: ubuntu
            version: 20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate Tag
        id: tag
        run: |
          echo ::set-output name=POST_TAG::$(date +%Y.%m.%d)
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          registry: containers.monetr.dev
          username: ${{ secrets.containers_push_username }}
          password: ${{ secrets.containers_push_password }}
          dockerfile: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
          path: images/${{ matrix.path }}/${{ matrix.version }}
          tags: latest,${{ matrix.version}},${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
          repository: ${{ matrix.path }}
      - name: Build and push ghcr.io
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
          path: images/${{ matrix.path }}/${{ matrix.version }}
          tags: latest,${{ matrix.version}},${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
          repository: monetr/build-containers/${{ matrix.path }}
